### ISSUE TITLE
Error on Data Request

### ISSUE THREAD

**Issue by nwrenger** [wrenger/schiller-lib#11]
Can the Server please send on errors fitting data for translations, the current translations can be found here: [locales](https://github.com/wrenger/schiller-lib/tree/rework/lib-view/src/lib/i18n/locales).

**Comment by nwrenger** [comment]
Done in this [commit](https://github.com/wrenger/schiller-lib/commit/78b841c7b987524b83e6a98e512e5a7048f71368)

**Comment by wrenger** [comment]
Honestly I still don't think that the server should be concerned with the translation logic. It just doesn't belong there!

Justification: Decisions like these lead to spaghetti code. If we want to change the internationalization somewhere in the future for whatever reason we now have to update both the UI and the server ([separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns)).

**Comment by nwrenger** [comment]
[done](https://github.com/wrenger/schiller-lib/commit/1d143238889c38419b1f32ccea608ca12b1bf4df)
